[package]
name = "fe-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
dialoguer = "0.8"
colored = "2"
git2 = "0.18.0"
indicatif = "0.17.6"
